<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");
use Bitrix\Main\Page\Asset;

Asset::getInstance()->addCss(SITE_TEMPLATE_PATH . "/css/order.min.css");

$request = \Bitrix\Main\Context::getCurrent()->getRequest();

$orderID = $request->get("ORDER_ID");
?>
<div class="custom-basket">
    <? if (!$orderID): ?>
        <script>window.basketJSParams = window.basketJSParams || [];</script>
        <?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"notaspro", 
	array(
		"COLUMNS_LIST" => array(
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "PROPS",
			3 => "DELETE",
			4 => "DELAY",
			5 => "TYPE",
			6 => "PRICE",
			7 => "QUANTITY",
			8 => "SUM",
		),
		"OFFERS_PROPS" => array(
			0 => "SIZES",
			1 => "COLOR_REF",
		),
		"BASKET_WITH_ORDER_INTEGRATION" => "N",
		"USE_PRICE_ANIMATION" => "N",
		"PATH_TO_ORDER" => SITE_DIR."order/",
		"HIDE_COUPON" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"USE_PREPAYMENT" => "N",
		"SET_TITLE" => "N",
		"AJAX_MODE_CUSTOM" => "Y",
		"SHOW_MEASURE" => "Y",
		"PICTURE_WIDTH" => "100",
		"PICTURE_HEIGHT" => "100",
		"SHOW_FULL_ORDER_BUTTON" => "Y",
		"SHOW_FAST_ORDER_BUTTON" => "Y",
		"COMPONENT_TEMPLATE" => "notaspro",
		"QUANTITY_FLOAT" => "N",
		"ACTION_VARIABLE" => "action",
		"TEMPLATE_THEME" => "blue",
		"AUTO_CALCULATION" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"USE_GIFTS" => "Y",
		"GIFTS_PLACE" => "BOTTOM",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MESS_BTN_DETAIL" => "Подробнее",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_CONVERT_CURRENCY" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N",
		"EMPTY_BASKET_HINT_PATH" => SITE_DIR."catalog/",
		"DEFERRED_REFRESH" => "N",
		"USE_DYNAMIC_SCROLL" => "Y",
		"SHOW_FILTER" => "Y",
		"SHOW_RESTORE" => "Y",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
		),
		"COLUMNS_LIST_MOBILE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
		),
		"TOTAL_BLOCK_DISPLAY" => array(
			0 => "top",
		),
		"DISPLAY_MODE" => "extended",
		"PRICE_DISPLAY_MODE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
		"LABEL_PROP" => array(
		),
		"CORRECT_RATIO" => "Y",
		"COMPATIBLE_MODE" => "Y",
		"ADDITIONAL_PICT_PROP_26" => "-",
		"ADDITIONAL_PICT_PROP_28" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"USE_ENHANCED_ECOMMERCE" => "N"
	),
	false
);?>
        <?$APPLICATION->IncludeComponent(
            "bitrix:main.include",
            "basket",
            array(
                "COMPONENT_TEMPLATE" => "basket",
                "PATH" => SITE_DIR."include/comp_basket_related_products.php",
                "AREA_FILE_SHOW" => "file",
                "AREA_FILE_SUFFIX" => "",
                "AREA_FILE_RECURSIVE" => "Y",
                "EDIT_TEMPLATE" => "standard.php",
                "PRICE_CODE" => array(
                    0 => "BASE",
                    1 => "OPT",
                ),
                "STORES" => array(
                    0 => "1",
                    1 => "2",
                    2 => "",
                ),
                "BIG_DATA_RCM_TYPE" => "personal",
                "STIKERS_PROP" => "HIT",
                "SALE_STIKER" => "SALE_TEXT"
            ),
            false
        );?>
    <? endif; ?>
    <?$APPLICATION->IncludeComponent(
        "bitrix:sale.order.ajax",
        "v1",
        array(
            "PAY_FROM_ACCOUNT" => "N",
            "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
            "COUNT_DELIVERY_TAX" => "Y",
            "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
            "ALLOW_AUTO_REGISTER" => "Y",
            "SEND_NEW_USER_NOTIFY" => "Y",
            "DELIVERY_NO_AJAX" => "Y",
            "DELIVERY_NO_SESSION" => "N",
            "TEMPLATE_LOCATION" => "popup",
            "DELIVERY_TO_PAYSYSTEM" => "d2p",
            "USE_PREPAYMENT" => "N",
            "PROP_1" => "",
            "PROP_3" => "",
            "PROP_2" => "",
            "PROP_4" => "",
            "SHOW_STORES_IMAGES" => "Y",
            "PATH_TO_BASKET" => SITE_DIR."basket/",
            "PATH_TO_PERSONAL" => SITE_DIR."personal/",
            "PATH_TO_PAYMENT" => SITE_DIR."order/payment/",
            "PATH_TO_AUTH" => SITE_DIR."auth/",
            "SET_TITLE" => "Y",
            "PRODUCT_COLUMNS" => "",
            "DISABLE_BASKET_REDIRECT" => "Y",
            "DISPLAY_IMG_WIDTH" => "90",
            "DISPLAY_IMG_HEIGHT" => "90",
            "COMPONENT_TEMPLATE" => "v1",
            "ALLOW_NEW_PROFILE" => "Y",
            "SHOW_PAYMENT_SERVICES_NAMES" => "Y",
            "COMPATIBLE_MODE" => "Y",
            "BASKET_IMAGES_SCALING" => "adaptive",
            "ALLOW_USER_PROFILES" => "Y",
            "TEMPLATE_THEME" => "blue",
            "SHOW_TOTAL_ORDER_BUTTON" => "Y",
            "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
            "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
            "SHOW_DELIVERY_LIST_NAMES" => "Y",
            "SHOW_DELIVERY_INFO_NAME" => "Y",
            "SHOW_DELIVERY_PARENT_NAMES" => "Y",
            "BASKET_POSITION" => "after",
            "SHOW_BASKET_HEADERS" => "Y",
            "DELIVERY_FADE_EXTRA_SERVICES" => "Y",
            "SHOW_COUPONS_BASKET" => "Y",
            "SHOW_COUPONS_DELIVERY" => "Y",
            "SHOW_COUPONS_PAY_SYSTEM" => "Y",
            "SHOW_NEAREST_PICKUP" => "N",
            "DELIVERIES_PER_PAGE" => "8",
            "PAY_SYSTEMS_PER_PAGE" => "8",
            "PICKUPS_PER_PAGE" => "5",
            "SHOW_MAP_IN_PROPS" => "Y",
            "SHOW_MAP_FOR_DELIVERIES" => array(
                0 => "1",
                1 => "2",
            ),
            "PROPS_FADE_LIST_1" => array(
                0 => "1",
                1 => "2",
                2 => "3",
                3 => "4",
                4 => "7",
            ),
            "PROPS_FADE_LIST_2" => array(
            ),
            "PRODUCT_COLUMNS_VISIBLE" => array(
                0 => "PREVIEW_PICTURE",
                1 => "PROPS",
                2 => "NOTES",
                3 => "DISCOUNT_PRICE_PERCENT_FORMATED",
                4 => "PRICE_FORMATED",
                5 => "PROPERTY_BRAND",
            ),
            "ADDITIONAL_PICT_PROP_13" => "-",
            "ADDITIONAL_PICT_PROP_14" => "-",
            "PRODUCT_COLUMNS_HIDDEN" => array(
                0 => "PREVIEW_PICTURE",
                1 => "DETAIL_PICTURE",
                2 => "PREVIEW_TEXT",
                3 => "PROPS",
                4 => "NOTES",
                5 => "DISCOUNT_PRICE_PERCENT_FORMATED",
                6 => "PRICE_FORMATED",
                7 => "PROPERTY_BRAND",
                8 => "PROPERTY_PROP_2033",
            ),
            "USE_YM_GOALS" => "N",
            "USE_CUSTOM_MAIN_MESSAGES" => "Y",
            "USE_CUSTOM_ADDITIONAL_MESSAGES" => "Y",
            "USE_CUSTOM_ERROR_MESSAGES" => "Y",
            "SHOW_ORDER_BUTTON" => "final_step",
            "SKIP_USELESS_BLOCK" => "Y",
            "SERVICES_IMAGES_SCALING" => "standard",
            "COMPOSITE_FRAME_MODE" => "A",
            "COMPOSITE_FRAME_TYPE" => "AUTO",
            "ALLOW_APPEND_ORDER" => "Y",
            "SHOW_NOT_CALCULATED_DELIVERIES" => "Y",
            "SPOT_LOCATION_BY_GEOIP" => "Y",
            "SHOW_VAT_PRICE" => "Y",
            "USE_PRELOAD" => "Y",
            "SHOW_PICKUP_MAP" => "Y",
            "PICKUP_MAP_TYPE" => "yandex",
            "USER_CONSENT" => "N",
            "USER_CONSENT_ID" => "0",
            "USER_CONSENT_IS_CHECKED" => "Y",
            "USER_CONSENT_IS_LOADED" => "N",
            "ACTION_VARIABLE" => "soa-action",
            "ADDITIONAL_PICT_PROP_135" => "-",
            "ADDITIONAL_PICT_PROP_136" => "-",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "EMPTY_BASKET_HINT_PATH" => "/",
            "USE_PHONE_NORMALIZATION" => "Y",
            "HIDE_ORDER_DESCRIPTION" => "N",
            "MESS_AUTH_BLOCK_NAME" => "Авторизация",
            "MESS_REG_BLOCK_NAME" => "Регистрация",
            "MESS_BASKET_BLOCK_NAME" => "Товары в заказе",
            "MESS_REGION_BLOCK_NAME" => "Тип покупателя и регион доставки",
            "MESS_PAYMENT_BLOCK_NAME" => "Способ оплаты",
            "MESS_DELIVERY_BLOCK_NAME" => "Способ доставки",
            "MESS_BUYER_BLOCK_NAME" => "Покупатель",
            "MESS_BACK" => "Назад",
            "MESS_FURTHER" => "Далее",
            "MESS_EDIT" => "изменить",
            "MESS_ORDER" => "Оформить заказ",
            "MESS_PRICE" => "Стоимость",
            "MESS_PERIOD" => "Срок доставки",
            "MESS_NAV_BACK" => "Назад",
            "MESS_NAV_FORWARD" => "Вперед",
            "MESS_PRICE_FREE" => "бесплатно",
            "MESS_ECONOMY" => "Экономия",
            "MESS_REGISTRATION_REFERENCE" => "Если вы впервые на сайте, и хотите, чтобы мы вас помнили и все ваши заказы сохранялись, заполните регистрационную форму.",
            "MESS_AUTH_REFERENCE_1" => "Символом \"звездочка\" (*) отмечены обязательные для заполнения поля.",
            "MESS_AUTH_REFERENCE_2" => "После регистрации вы получите информационное письмо.",
            "MESS_AUTH_REFERENCE_3" => "Личные сведения, полученные в распоряжение интернет-магазина при регистрации или каким-либо иным образом, не будут без разрешения пользователей передаваться третьим организациям и лицам за исключением ситуаций, когда этого требует закон или судебное решение.",
            "MESS_ADDITIONAL_PROPS" => "Дополнительные свойства",
            "MESS_USE_COUPON" => "Применить купон",
            "MESS_COUPON" => "Купон",
            "MESS_PERSON_TYPE" => "Тип плательщика",
            "MESS_SELECT_PROFILE" => "Выберите профиль",
            "MESS_REGION_REFERENCE" => "Выберите свой город в списке. Если вы не нашли свой город, выберите \"другое местоположение\", а город впишите в поле \"Город\"",
            "MESS_PICKUP_LIST" => "Пункты самовывоза:",
            "MESS_NEAREST_PICKUP_LIST" => "Ближайшие пункты:",
            "MESS_SELECT_PICKUP" => "Выбрать",
            "MESS_INNER_PS_BALANCE" => "На вашем пользовательском счете:",
            "MESS_ORDER_DESC" => "Комментарии к заказу:",
            "MESS_SUCCESS_PRELOAD_TEXT" => "Вы заказывали в нашем интернет-магазине, поэтому мы заполнили все данные автоматически. Если все заполнено верно, нажмите кнопку \"#ORDER_BUTTON#\".",
            "MESS_FAIL_PRELOAD_TEXT" => "Вы заказывали в нашем интернет-магазине, поэтому мы заполнили все данные автоматически. Обратите внимание на развернутый блок с информацией о заказе. Здесь вы можете внести необходимые изменения или оставить как есть и нажать кнопку \"#ORDER_BUTTON#\".",
            "MESS_DELIVERY_CALC_ERROR_TITLE" => "Не удалось рассчитать стоимость доставки.",
            "MESS_DELIVERY_CALC_ERROR_TEXT" => "Вы можете продолжить оформление заказа, а чуть позже менеджер магазина свяжется с вами и уточнит информацию по доставке.",
            "MESS_PAY_SYSTEM_PAYABLE_ERROR" => "Вы сможете оплатить заказ после того, как менеджер проверит наличие полного комплекта товаров на складе. Сразу после проверки вы получите письмо с инструкциями по оплате. Оплатить заказ можно будет в персональном разделе сайта."
        ),
        false
    );?>

    <? if (!$orderID): ?>
    <?$APPLICATION->IncludeComponent(
        "bitrix:main.include",
        "basket",
        array(
            "COMPONENT_TEMPLATE" => "basket",
            "PATH" => SITE_DIR."include/comp_basket_bigdata.php",
            "AREA_FILE_SHOW" => "file",
            "AREA_FILE_SUFFIX" => "",
            "AREA_FILE_RECURSIVE" => "Y",
            "EDIT_TEMPLATE" => "standard.php",
            "PRICE_CODE" => array(
                0 => "BASE",
                1 => "OPT",
            ),
            "STORES" => array(
                0 => "1",
                1 => "2",
                2 => "",
            ),
            "BIG_DATA_RCM_TYPE" => "personal",
            "STIKERS_PROP" => "HIT",
            "SALE_STIKER" => "SALE_TEXT"
        ),
        false
    );?>
    <? endif; ?>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>